### ISSUE TITLE
No License, Lawsuit averse will not use.

### ISSUE THREAD

**Issue by Sqeaky** [Uduse/Escape-Sequence-Color-Header#1]
Without a license even the most fantastic code, and this seems pretty good, cannot be used by conservative organizations. In many Western jurisdictions "copyright with all rights reserved" is the default license. Than means that many will assume that you don't want others to use your code, even though it seems you want others to use it.

If you want maximum proliferation of you code consider the BSD two clause license: http://opensource.org/licenses/BSD-2-Clause

Add the contents of the license template to a LICENSE.txt or COPYING.txt file (or .md) and add a copyright notice to each source file at the top.

If you want I can make a pull request with the license of you choice: http://opensource.org/licenses/category

Just pick one and let me know.

**Comment by uduse** [comment]
Thank you for your interest!

I have no previous experience with licenses, but the BSD two clause license seems good to me!

If you can make a pull request for that, that will be awesome! Thanks in advance!

**Comment by Sqeaky** [comment]
I will do that.
